import { UserContextProvider }  from "@/context/UserContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { Suspense } from "react";
import HeaderComponent from "@/components/ui/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const token = cookieStore.get('token')?.value;
  const isAuthenticated = (token !== null) && (token !== undefined) && (token !== '');
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Web site created using create-react-app" />
        <meta name="author" content="Your Name" />
        <meta name="keywords" content="art, gallery, exhibitions, artists, pieces" />
        <meta name="title" content="ArtsyHub WebPage" />
      </head>
      {(isAuthenticated)  && (
        <HeaderComponent />
      )}
      <body
        className='font-sans bg-white'
      >
        <Suspense fallback={<div>Loading...</div>}> 
          {children}
        </Suspense>
      </body>
    </html>
  );
}
